# -*- coding: utf-8 -*-
"""Identification_of_Huntingtons_Disease

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_ltIBNjf5NSbMAA5HpS_BYovRhOgACl
"""

from collections import Counter
import sys
def find_tandem_repeats(sequence, search):
    if sequence == '' or search == '':
        return

    lengths = list(map(len, sequence.split(search)))
    pos = lengths[0]
    repeats = 0
    pending = False

    for l in lengths[1:]:
        if l == 0:
            pending = True
            repeats += 1
            continue
        repeats += 1
        yield (pos, repeats)
        pos += l + len(search) * repeats
        repeats = 0
        pending = False

    if pending:
        yield (pos, repeats)
a=["Difficulty in Concentrating","Stumbling and Clumsiness","Mood Swings"]
a1=["Increasingly Slow or Rigid Movements","Involuntary Jerking or Fidgety Movements of the Limbs And Body","Breathing Problems","Difficulty Moving Around","Swallowing Problems"]
b=input("Enter your Name: ")
c=int(input("Enter your Age: "))
d=input("Your Gender: ")
print("Symptoms: ")
for i in range(0,len(a)):
  print(i+1,"-",a[i])
q1=int(input("How many of the above symptoms are you facing? "))
total=len(a)
if(q1>total):
  sys.exit("Error message")
for i in range(len(a1)):
  print(i+1,"-",a1[i])
q2=int(input("How many of the above symptoms are you facing? "))
total1=len(a1)
if(q2>total1):
  sys.exit("Error message")
pt=q1*1+q2*3
wait=0
if pt<=2:
  print("You are healthy")
elif (pt>2 and pt<=9):
  print("You are Having some symptoms")
  p=input("Are You Willing to proceed for a blood test(Y(Yes)/N(No)): ")
  if (p=="Y"):
    wait+=1
else:
  print("You are having some serious Symptoms\nWe advice you to perform a blood test")
  wait+=1
if (wait==1):
  file1=open("/content/htt human gene2.txt", "r")
  r=file1.read()
  positions = list(find_tandem_repeats(r, 'CAG'))
  max_position = max(positions, key=lambda x: x[1])
  print("Number of repeats is %s" % max_position[1])
  if(max_position[1]>35):
    print("You have High Chance of Having Huntington's Disease")
  elif(max_position[1]>27&max_position[1]<=35):
    print("You have Intermediate Chance of Having Huntington's Disease")
  else:
    print("You have Low Chance of Having Huntington's Disease")